#!/usr/bin/env python3
"""
Generate requirements-secure.txt with versioned, hashed pins for secure-pm bootstrap.
Run this to re-audit the tool'\''s own dependencies.
"""
import sys
import re
sys.path.insert(0, ".")
from talkdoc_secure_pm.managers.pip_manager import PipManager

def main():
    mgr = PipManager()
    deps = ["requests", "openai", "rich", "python-dotenv", "packaging"]
    print("Auditing secure-pm dependencies for bootstrap...")
    
    with open("requirements-secure.txt", "w") as f:
        f.write("# Audited and pinned dependencies for secure-pm bootstrap (with versions)\n")
        f.write("# Generated by generate_secure_reqs.py - re-run after dependency changes\n\n")
        
        for dep in deps:
            print(f"Processing {dep}...")
            is_safe, hashes = mgr.audit_only(dep)
            print(f"  {dep}: safe={is_safe}, hashes={len(hashes)}")
            if is_safe and hashes:
                for filename, h in hashes.items():
                    # Parse version from filename (PEP 440 style)
                    version_match = re.search(r"-([0-9][0-9a-zA-Z._+]*?)(?:-|\.tar|\.whl|\.zip|$)", filename)
                    version = version_match.group(1) if version_match else "0.0.0"
                    pkg = re.split(r'-(?=\d)', filename)[0]
                    f.write(f"{pkg}=={version} --hash=sha256:{h}\n")
    
    print("Generated requirements-secure.txt with versioned pins.")
    print("Use: pip install -r requirements-secure.txt --require-hashes")

if __name__ == "__main__":
    main()
