#!/usr/bin/env python3
"""
Standalone generator for requirements-secure.txt.
Uses pip download with CI-matching platform tags to fetch all transitive wheels/hashes.
No project imports needed - pure stdlib.
"""
import os
import re
import sys
import subprocess
import tempfile
import shutil
import hashlib

def main():
    direct_deps = ["requests==2.33.0", "openai==2.30.0", "rich==14.3.3", "python_dotenv==1.2.2", "packaging==26.0"]
    print("Generating secure bootstrap reqs matching CI (Ubuntu/Python 3.12 x64)...")
    temp_dir = tempfile.mkdtemp(prefix='secure-reqs-')
    try:
        # pip download with tags for CI compat, no cache, fetch deps
        pip_cmd = [
            sys.executable, "-m", "pip", "download",
            "--dest", temp_dir,
            "--no-cache-dir",
            "--platform", "manylinux2014_x86_64",
            "--implementation", "cp",
            "--abi", "cp312",\n            "--python-version", "3.12"
        ]
        subprocess.check_call(pip_cmd + direct_deps, timeout=300)
        print(f"Downloaded to {temp_dir}")
        
        all_pins = {}
        for root, dirs, files in os.walk(temp_dir):
            for filename in files:
                if filename.endswith(('.whl', '.tar.gz')):
                    archive_path = os.path.join(root, filename)
                    hash_digest = hashlib.sha256(open(archive_path, 'rb').read()).hexdigest()
                    
                    # Parse pkg/version from filename
                    pkg_match = re.match(r'^(.*?)-', filename)
                    pkg = pkg_match.group(1) if pkg_match else filename
                    ver_match = re.search(r'-([\d\w._+-]+?)(?=\.(whl|tar\.gz)|-|$)', filename)
                    version = ver_match.group(1) if ver_match else "0.0.0"
                    
                    all_pins[filename] = (pkg, version, hash_digest)
        
        with open("requirements-secure.txt", "w") as f:
            f.write("# Full transitive bootstrap pins for secure-pm (CI-compatible)\\n")
            f.write("# Generated by generate_secure_reqs_standalone.py\\n")
            f.write("# Re-run to refresh hashes\\n\\n")
            for filename in sorted(all_pins):
                pkg, version, h = all_pins[filename]
                f.write(f'{pkg}=={version} --hash=sha256:{h}\\n')
        
        print(f"✅ Generated requirements-secure.txt with {len(all_pins)} pinned deps (transitives included).")
        print("Test: pip install -r requirements-secure.txt --require-hashes --dry-run")
    except subprocess.CalledProcessError as e:
        print(f"❌ Download failed: {e}")
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)

if __name__ == '__main__':
    main()

